version: "3.7"
services:

  nginx:
    image: nginx:1.19.5
    networks:
      - gis_2ban_network
    volumes:
      - gis_2ban_media:/data/media/
      - gis_2ban_static:/data/static/
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  django:
    image: gis_2ban_django:5
    networks:
      - gis_2ban_network
    volumes:
      - gis_2ban_media:/home/Pragmatic_/pragmatic/media/
      - gis_2ban_static:/home/Pragmatic_/pragmatic/staticfiles/

  mariadb:
    image: mariadb:10.5
    networks:
      - gis_2ban_network
    volumes:
      - gis_mariadb:/var/lib/mysql
    environment:
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: ckdwns4028
      MARIADB_ROOT_PASSWORD: ckdwns4028


networks:
  gis_2ban_network:

volumes:
  gis_2ban_media:
  gis_2ban_static:
  gis_mariadb:
